name: Release, Build and Publish Artifact
on:
  pull_request:
    types: [closed]
jobs:
  release:
    uses: lowranceworks/common-workflows/.github/workflows/releases/create-tag-and-release.yaml@main
    permissions:
      contents: write
      pull-requests: read
      issues: read

  build:
    needs: release
    if: success() && github.event.pull_request.merged == true
    uses: ticketing-platform/common-workflows/.github/workflows/artifacts/zip-to-artifactory.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
