name: Semver Label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-semver-label:
    uses: lowranceworks/common-workflows/.github/workflows/semver-label.yaml@main
    permissions:
      issues: write
      pull-requests: write
      contents: read
